
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon May 15 13:12:27 BST 2017
//----------------------------------------------------

package Example;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int LSQBRACKET = 4;
  public static final int COLON = 3;
  public static final int LCBRACKET = 6;
  public static final int NUMBER = 9;
  public static final int BOOLEAN = 11;
  public static final int NULL = 8;
  public static final int RSQBRACKET = 5;
  public static final int STRING = 10;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int COMMA = 2;
  public static final int RCBRACKET = 7;
}

